FROM php:7.2-apache
USER root
WORKDIR /var/www/html/
COPY --chown=root:root ./ ./
RUN docker-php-ext-install mysqli > /dev/null
RUN docker-php-ext-enable mysqli > /dev/null
RUN cp application/config/exemplo.database.php application/config/database.php
RUN chown -R www-data:www-data assets/uploads/
RUN a2enmod rewrite > /dev/null
RUN apachectl restart > /dev/null
RUN echo "Production Deploy Successfully!"